### ISSUE TITLE
Zápis schůze z 26. 10. 2017

### ISSUE THREAD

**Issue by repli2dev** [zverinec/zverinec-docs#2]

**Comment by Krejdom** [comment]
Prosím o kontrolu, je to ve větvi wip-2017-i

**Comment by mukrop** [comment]
Komentare odo mna a @repli2dev najdes v commite dd11d2540.

**Comment by mukrop** [comment]
@Krejdom Prosim doplnis zmeny do zapisu podla poznamok a urobis merge?

**Comment by Krejdom** [comment]
@mukrop Už jsem to doplnila, je ještě něco, co tam chybí?

**Comment by mukrop** [comment]
To som si vsimol az potom. Za mna je tam vsetko, mozes ma uviest ako kontrolu.
@repli2dev, @horacekj?

**Comment by malinajan** [comment]
ACK.

**Comment by mukrop** [comment]
Doplnene na web.
